# ------------------------------------------------Environment Settings------------------------------------------------#
gpu_id: "0,1,2,3,4,5,6,7"
# gpu_id: "0,1,2,3"


# -------------------------------------------------Retrieval Settings------------------------------------------------#
# If set the name, the model path will be find in global paths
retrieval_method: "intfloat/e5-base-v2"  # name or path of the retrieval model.
index_path: "/path/to/your/indexes/e5_flat_inner.index"  # path to your FAISS index file
faiss_gpu: True # whether use gpu to hold index
corpus_path: "/path/to/your/retrieval_corpus/wiki.jsonl"  # path to the retrieval corpus in '.jsonl' format
